### ISSUE TITLE
自動マージの設定

### ISSUE THREAD

**Issue by shoo** [dlang-jp/Cookbook#122]
プルリクエストの自動マージを導入してはいかがでしょう。
比較的簡単にできそうな案としては以下の条件を満たしたときに自動的にマージ
- マージ前に Pull Request レビュー必須
- マージ前にステータスチェック必須

以下参考
https://docs.github.com/ja/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches
https://docs.github.com/ja/github/administering-a-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository

**Comment by lempiji** [comment]
:+1:

**Comment by shoo** [comment]
ブランチの保護と、自動マージボタンを有効にしてみました。
詳細は設定からご確認ください。
しばらく運用してみて、うまくいきそうならクローズします

**Comment by shoo** [comment]
↓自動マージされた例
https://github.com/dlang-jp/Cookbook/pull/121
