### ISSUE TITLE
dmd 2.098.0 でコンパイルエラーが発生する

### ISSUE THREAD

**Issue by shoo** [dlang-jp/Cookbook#143]
このため、しばらくの間自動テストは通らなくなりそうです。
dmdのリグレッションが原因のようで、すでに解決のためのPRがマージ済みのようです。2.098.1で改善するでしょう。

https://issues.dlang.org/show_bug.cgi?id=22420

**Comment by kubo39** [comment]
これは2.098.1リリースしたので解決？

**Comment by shoo** [comment]
2.098.1で解決です！
