### ISSUE TITLE
ldc-1.29.0でlibdparseのサンプルのテストが通らない

### ISSUE THREAD

**Issue by shoo** [dlang-jp/Cookbook#157]
以下の問題に起因していそう。ldc-1.28.0ではうまくいくので、おそらくldcのリグレッション。
https://github.com/ldc-developers/ldc/issues/3950

**Comment by outlandkarasu** [comment]
libdparseでの問題解消後に`version(none)`解除が必要です。

**Comment by outlandkarasu** [comment]
こちらが解消された復活する。

https://github.com/dlang-community/libdparse/issues/457

**Comment by kubo39** [comment]
https://github.com/dlang-community/libdparse/releases/tag/v0.19.2　修正版がリリースされました。
