### ISSUE TITLE
著作権ライセンスについての質問

### ISSUE THREAD

**Issue by hmjfk** [dlang-jp/Cookbook#204]
このプロジェクトにはオープンソースライセンスに関する記述が全く見当たりません。ここにあるソースコードやドキュメントはどのようにライセンスされていますか？そのままであれば、日本の著作権法に基づいてすべての権利が保護されている状態なので、二次利用ができません。

**Comment by lempiji** [comment]
動作するコードを広く共有することが目的であり、気になるコードはコピペして利用ください。二次利用でも特に引用を示す必要はありません。

具体的なライセンスについては記載検討するので少しお待ちください。

**Comment by lempiji** [comment]
コントリビューター各位 @shoo @outlandkarasu @kubo39 @simdnyan @kotet 

これを機にリポジトリにライセンスを設定したいと思います。
好きにコピペして良いという話から、利用表記が不要という条件は必要と考えています。

問題なければ1週間後の2024-03-21(木)を目途にpublic domainに設定しますので、それまでにご意見いただけますでしょうか
またもし、CC0が良いという声があればそちらに切り替えます。（違いは商標と特許を禁止するくらい）

public domainの場合: https://github.com/dlang-jp/Cookbook/community/license/new?branch=master&filename=LICENSE&template=unlicense
CC0の場合: https://github.com/dlang-jp/Cookbook/community/license/new?branch=master&filename=LICENSE&template=cc0-1.0

**Comment by shoo** [comment]
https://github.com/dlang-jp/Cookbook/blob/685dd38f0b31111972b5ec06ed9c1d5df0c98648/dub.sdl#L4
実は元からpublic domainなので、public domainでいいと思います。
ただ、それをわかりやすく明示するためのライセンス文書(LICENSEファイル)は https://licenses.opensource.jp/ から選んだほうがいいでしょう。
public domain相当は [The Unlicense](https://licenses.opensource.jp/Unlicense/Unlicense.html) ([原文](https://opensource.org/licenses/Unlicense)) なのでこれを選ぶのがいいと思います。
→ つまり https://github.com/dlang-jp/Cookbook/community/license/new?branch=master&filename=LICENSE&template=unlicense
