### ISSUE TITLE
トップページに日本語タイトルをつけたい

### ISSUE THREAD

**Issue by lempiji** [dlang-jp/Cookbook#72]
トップページに `hoge_example` という見出しが並んでいるのはちょっと素っ気ないので、モジュールのdoccommentの1行目を表示するようにしたい。

`string_example` ⇒ `文字列操作`、などにして、サイドバーの見出しも同じで良いと思う。

mustacheの変更で済むのか、gendocにも手を入れる必要があるのか不明だったので方針の相談です。

**Comment by lempiji** [comment]
プロジェクト的には `module xxx;`が出てくるまでの行をパースして、`/++ `のあとに続く段落取り出せば十分な気がしますね。
syntaxコンパイルすればAutherとかSinceの情報が抜けるなら何等か使い道はありそうですが、見る分にはそこまで必要な気もしないのもあり。（書く人のモチベーションにはなるかもですが）

あと考えられるとすれば、コンテンツを作るときにdoc.jsonあたりにモジュール情報を保存しておいて、mustacheからその辺参照できるようにするとかですかね。
ddoxはSyntaxコンパイルして作ったjsonを加工して使っているので、大体似たようなことになってくるかもしれませんが

**Comment by Sobaya007** [comment]
私的には2案推しです
ドキュメント生成時にかかる時間は現状無視できる程度だと思うので、より多くの情報を抜ける選択肢を用意しておいたほうがいいと思います

**Comment by shoo** [comment]
2案で行こうと思います。
ただし、コンパイル時間は確実に増加するので、設定で無効化できるようにしておきます。JSONファイルの出力有無って感じに。
ただし、JSONから拾える情報はDDocマクロが混入していても展開されませんし、コメント全文が拾われるので、最初の改行または末尾まで、という感じで概要文をstripした状態で抽出しようとおもいます。

- 設定ファイルの`enableGenerateJSON`をtrueでJSON生成＆タイトル抽出を有効化(デフォルトtrue)
- JSONファイルを生成する場合はdocsフォルダ内にdubパッケージ名の`:`を`-`に変換し、`.json`拡張子をつけた名称で生成する。
- コンパイルで`-o-`、`-X`、`-D`および`-Xf`で上記ファイル出力先を付与して生成されるJSONからモジュールに対するコメントを抽出する。
- JSONから得られるコメントをsplitLinesし、1行目をstripしてタイトルを抽出する。
- `*.mustache`の`{{# is_module}}`セクション内にて、`{{module_title}}` で上記タイトルが利用できるようにする。
- デフォルトで含まれる `_module_info.mustache` に上記 `{{module_title}}` を追加する。

例えば…

```
/++
 + あいう$(A え)お
 + かきくけこ
 + 
 + さしすせそたちつてと
 +/
```

上記からは、以下のJSONの文字列が得られます。(※行頭にはコメント内のインデント用スペースが含まれます)

```
 あいう$(A え)お
 かきくけこ
 
 さしすせそたちつてと
```

ここから、`あいう$(A え)お`を抽出します。DDocのSummaryセクションと厳密には異なることに注意してください。

もしも上記タイトル以上のものが欲しい場合は、JSONを使用して頑張ってくださいって方針です。`{{# command}}`とか`{{# rdmd}}`ていうこないだ追加した新しいセクション使えばかなり無茶できるはずです。

それと、LDCの場合は実のところすでにJSONファイルを生成して情報とっているので、あまり実行時間変わらないかもしれません。これは`-oq`オプション(出力するHTMLファイルにパッケージ名も含めるオプション)があるため可能となっています。dmdにもこれがあればいいのに…。

**Comment by shoo** [comment]
https://github.com/shoo/gendoc/issues/7
