### ISSUE TITLE
ドキュメントからGitHubに飛ぶためのリンクがほしい

### ISSUE THREAD

**Issue by lempiji** [dlang-jp/Cookbook#95]
GitHubトップに飛ぶリンクを用意しておきたい
できればページ毎にソースリンクしたい

**Comment by shoo** [comment]
Phobosではmoduleのコメントでソースコードへのリンクをこんな感じに定義しています
```
Source: $(PHOBOSSRC std/algorithm/package.d)
```
自動でリンクをつけるより、手動でやったほうがいいのかな？
